import Head from "next/head";
import styles from "../styles/Home.module.css";
import MyTodos from "../components/MyTodos";
import { RedirectToSignIn, SignedOut, UserButton } from "@clerk/nextjs";
import { useAuth } from "@clerk/nextjs";
import { useEffect } from "react";

export default function Home() {
  const { isLoaded, userId, sessionId } = useAuth();
  console.log({ isLoaded, userId, sessionId });

  return (
    <div className={styles.container}>
      <Head>
        <title>My Todos</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <UserButton
          afterSignOutUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL}
        />
      </header>
      <main className={styles.main}>
        <MyTodos />
      </main>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
    </div>
  );
}
