import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import MyTodos from "../components/MyTodos";
import { UserButton } from "@clerk/nextjs";
import { useAuth } from "@clerk/nextjs";

export default function Home() {
  const { isLoaded, sessionId } = useAuth();
  const { push } = useRouter();

  if (!isLoaded) {
    return <>Loading...</>;
  }

  if (isLoaded && !sessionId) {
    return push("/signin");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>My Todos</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <UserButton
          afterSignOutUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL}
        />
      </header>
      <main className={styles.main}>
        <MyTodos />
      </main>
    </div>
  );
}
